name = "actual-fyi-forensic"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[env.production.vars]
# Secret keys are managed in the Cloudflare Dashboard
