
name = "actual-fyi-forensic"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[site]
bucket = "./dist"

[env.production.vars]
# Secret keys are managed in the Cloudflare Dashboard
